version: '3'

services:
  web:
    container_name: ${APP_URL}-web
    build: ./docker/php-apache
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html
      - ./docker/php-apache/logs:/var/log/apache2
      - ./docker/php-apache/vhosts/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
  
